# Generated by Django 3.1.4 on 2020-12-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20201219_2016'),
        ('resume', '0003_resume_user'),
    ]

    operations = [
    ]
