# Generated by Django 3.0.6 on 2020-12-20 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0005_certificate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='interests',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certi_resume', to='resume.Resume'),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('city_country', models.CharField(max_length=150)),
                ('role_resposibility', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workexp_resume', to='resume.Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workexp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('project_desc', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_resume', to='resume.Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=150)),
                ('institute_name', models.CharField(max_length=150)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('gpa', models.CharField(max_length=10)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_resume', to='resume.Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=150)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('achievement_desc', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_resume', to='resume.Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
