# Generated by Django 3.0.6 on 2020-12-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20201220_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='resume.Resume'),
        ),
    ]
