# Generated by Django 3.1.4 on 2020-12-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20201220_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='role_resposibility',
            new_name='role_responsibility',
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workExperiences', to='resume.resume'),
        ),
    ]
