# Generated by Django 3.1.4 on 2020-12-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20201220_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
