# Generated by Django 3.1.4 on 2020-12-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_resume_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='designation',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
