# Generated by Django 3.1.4 on 2020-12-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20201225_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalproject',
            name='project_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institute_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='education',
            name='program_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='github_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='city_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
