# Generated by Django 3.1.4 on 2021-01-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20210103_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personalproject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='user',
        ),
    ]
